active_wrapper-solo:
  repo: git@github.com:bertrandk/active_wrapper.git
  path: vendor
also_migrate:
  repo: git@github.com:bertrandk/also_migrate.git
  path: vendor
framework_fixture:
  repo: git@github.com:winton/framework_fixture.git
  path: vendor
mover:
  repo: git@github.com:bertrandk/mover.git
  path: vendor